project:
  type: book
  output-dir: docs

book:
  title: "Business Analytics & Coding"
  description: "Eine kurze Einführung für Studierende der Betriebswirtschaftslehre"
  chapters:
    - index.qmd
    - part: Chapters/01_Chapter/Einleitung.qmd
      chapters:
      - Chapters/01_Chapter/Was_ist_BA.qmd
      - Chapters/01_Chapter/Coding.qmd
      - Chapters/01_Chapter/Warum_Python.qmd
    - part: Chapters/02_Chapter/Getting_Ready.qmd
      chapters:
      - Chapters/02_Chapter/Installation.qmd
      - Chapters/02_Chapter/Introduction_notebook.qmd
      - Chapters/02_Chapter/Python_Basics.qmd
    #- Chapters/03_Chapter/Fallstudie_1.qmd
    #- part: Chapters/04_Chapter/Deskriptive_Analyse.qmd
    #  chapters:
    #  - Chapters/04_Chapter/Deskriptive_Problemstellung.qmd
    #  - Chapters/04_Chapter/Einlesen_Aufbereiten.qmd
      #- Chapters/03_Chapter/Predictive_Analytics.qmd
      #- Chapters/03_Chapter/Prescriptive_Analytics.qmd
    - references.qmd
    #- part: Appendices/Anhang.qmd
    #  chapters:
    #  - Appendices/Modules/Pandas.qmd

  page-navigation: true
  sidebar: 
    collapse-level: 1
    search: true
    title: Inhalt

    
  reader-mode: true
  
  page-footer: 
    center: 
    - text: "© 2023 by F. Zeidler"

bibliography: references.bib

format:
  html:
    theme: [default, mystyle.scss]
    lang: de
    toc: true
    toc-depth: 4
    number-sections: False
    number-depth: 1
    text-algin: justify
    linestretch: 1.75
    fig-cap-location: bottom
    page-layout: full # Do I need this?
    reference-location: margin
    mathjax: true



