# VORWORT {.unnumbered .no-toc}


Bei diesem Skript handelt es sich um Selbstlernmaterial zum Thema __Datenanalyse__. Noch konkreter beschäftigt sich dieses Skript mit __Business Analytics__. Das Skript wurde neu konzipiert und richtet sich explizit an _Studierende der Betriebswirtschaftlehre_. Aktuell "atmet" das Dokument noch, d.h. Aktualisierungen und Ergänzungen sind sehr wahrscheinlich. Auch werden perspektivisch fortgeschrittenere Themenblöcke zum Bereich der __Predictive Analytics__ ergänzt werden. 

Das Skript ist explizit mit dem Ziel verfasst, als Selbstlernmaterial verwendet zu werden. Zumindest ist dies beim Verfassen des Skripts immer meine ausdrückliche Intention gewesen. Alle Code-Beispiele können via Knopfdruck selbst ausprobiert und adaptiert werden. Das Dokument ist somit zu Teilen interaktiv und sollte deshalb auch nicht nur passiv konsumiert werden. 

Ob mein Vorhaben tatsächlich gelungen ist, können schlussendlich nur Sie beurteilen. Sollten Sie also Fragen oder Anmerkungen bzw. technische Probleme haben oder - und dies bleibt leider nie aus - Fehler entdecken, dann bin ich dankbar für Ihr Feedback. Sprechen Sie mich entweder in den Veranstaltungen zum Modul direkt an oder schreiben mir eine Email (`felix.zeidler[at]fh-bielefeld.de`). Auch wenn es mir vermutlich nicht immer gelingen wird, Ihnen direkt zu antworten, bin ich dankbar für jede Art von Rückmeldung. 

Viel Spaß beim Lesen und Ausprobieren!

Prof. Dr. Felix Zeidler